{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "easywork.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "easywork.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "easywork.selectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
{{- end }}
